version: 2

models:
  - name: stg_orders
    columns:
      - name: order_id
        data_tests:
          - not_null
          - unique

  - name: customer_sales
    columns:
      - name: customer_id
        data_tests:
          - not_null
          - unique